version: 2

defaults: &defaults
  working_directory: ~/qlik-share-button
  docker:
    - image: circleci/node:stretch-browsers
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "Dashboard-Link-Generator"
    PACKAGE_NAME: "qlik-share-button"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: BlackDuck scan
          command: curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh | bash -s -- \
            --blackduck.url="https://qliktech.blackducksoftware.com" \
            --blackduck.trust.cert=true \
            --blackduck.username="svc-blackduck" \
            --blackduck.password=${svc_blackduck} \
            --detect.project.name="Dashboard-Link-Generator"
      - run:
          name: Build
          command: |
            npm run build:zip
            sudo chmod +x ./.circleci/verify-files.sh
            ./.circleci/verify-files.sh
      - persist_to_workspace:
          root: ~/qlik-share-button
          paths:
            - dist
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-share-button
      - run:
          name: Install GHR
          command: |
            sudo chmod +x ./.circleci/install-ghr.sh
            ./.circleci/install-ghr.sh
      - run:
          name: Create github release
          command: |
            sudo chmod +x ./.circleci/get-package-version.sh
            export PACKAGE_VERSION=$(./.circleci/get-package-version.sh)
            echo "Version: ${PACKAGE_VERSION}"
            sudo chmod +x ./.circleci/create-release.sh
            ./.circleci/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME $PACKAGE_VERSION

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /v.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/
